config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  # root "articles#index"

  resources :recipes do
    member do
      delete :destroy
      get 'add_ingredient', to: 'recipes#add_ingredient'
      post 'add_ingredient', to: 'recipes#add_ingredient'
      get 'generate_shopping_list', to: 'recipes#generate_shopping_list'
      delete 'remove_food'
    end
  end

  resources :foods do
   
    delete :destroy, on: :member
  end

  get 'public_recipes/index'
  get 'public_recipes/show'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
  before_validation :set_default_price

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :quantity, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  private

  def set_default_price
    self.price ||= 0
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
  belongs_to :user

  attribute :public, :boolean, default: false
  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, foreign_key: :user_id
  has_many :foods, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_food, only: %i[show destroy]

  def index
    @foods = current_user.foods
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user

    if @food.save
      redirect_to foods_path, notice: 'Food item was successfully created.'
    else
      flash.now[:alert] = 'Food item could not be saved due to the following errors:'
      render :new
      puts 'Not saved'
      Rails.logger.error("Validation errors: #{@food.errors}")
    end
  end

  def destroy
    if @food.destroy
      redirect_to foods_path, notice: 'Food item was successfully created.'
    else
      flash.now[:alert] = 'Food item could not be deleted.'
      render :show
    end
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.includes(:recipe_foods, :foods, :user).where(public: true)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
  end

  def add_ingredient
    @recipe = Recipe.left_outer_joins(:recipe_foods).select('recipes.*,recipe_foods.quantity').find(params[:id])

    if current_user == @recipe.user
      @foods_not_in_recipe = Food.where.not(id: @recipe.foods.pluck(:id))

      if params[:recipe].present? && params[:recipe][:food_ids].present?
        food_ids = params[:recipe][:food_ids].reject(&:empty?) # Remove empty strings
        Food.where(id: food_ids).each do |food|
          RecipeFood.create!(food:, recipe: @recipe, quantity: params[:recipe][:quantity])
        end
        flash[:notice] = 'Ingredients added successfully.'
        redirect_to @recipe
        return
      end
    else
      flash[:alert] = 'You do not have permission to add ingredients to this recipe.'
    end

    render 'add_ingredient'
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = @recipe.user
    @recipe_food = @recipe.foods.joins(:recipe_foods).select('foods.*,recipe_foods.quantity').distinct
  end

  def update
    @recipe = Recipe.find_by(id: params[:id])

    if @recipe.user == current_user

      @recipe.update(public: !@recipe.public)

      flash[:notice] = @recipe.public ? 'Recipe is now public.' : 'Recipe is now private.'
    else
      flash[:alert] = 'You do not have permission to toggle this recipe.'
    end
    redirect_to @recipe
  rescue StandardError => e
    flash[:notice] = "An error occurred: #{e.message}"
  end

  def remove_food
    @recipe = Recipe.find_by(id: params[:id])
    @recipe_food = RecipeFood.find_by(food_id: params[:food_id], recipe_id: params[:id])

    begin
      if current_user == @recipe.user
        RecipeFood.delete(@recipe_food)

        flash[:notice] = 'Ingredient removed successfully.'
      else

        flash[:alert] = 'You do not have permission to remove ingredients from this recipe.'
      end

      redirect_to @recipe
    rescue StandardError => e
      flash[:notice] = "An error occurred: #{e.message}"
    end
  end

  def public_recipes
    @public_recipes = Recipe.where(public: true).includes(:foods)
    @total_food_items = Food.sum(:quantity)
    @total_price = Food.joins(:recipe_foods).sum('foods.quantity * foods.price')
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    begin
      if @recipe.save
        flash[:notice] = 'Recipe created successfully.'
        redirect_to recipe_path(@recipe)

      else
        flash.now[:alert] = 'Recipe creation failed.'

        redirect_to new_recipe_url
      end
    rescue StandardError => e
      flash[:notice] = "An error occurred: #{e.message}"
    end
  end

  def generate_shopping_list
    @recipe = Recipe.find(params[:id])

    # Select all the foods associated with the current recipe through recipe_foods
    @required_foods = @recipe.recipe_foods.map(&:food)

    @total_value = @required_foods.sum { |food| food.quantity.to_i * food.price.to_f }
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.user == current_user
      @recipe.recipe_foods.destroy_all

      @recipe.destroy
      flash[:notice] = 'Recipe deleted successfully.'
    else
      flash[:alert] = 'You do not have permission to delete this recipe.'
    end
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<h2>This is foods page</h2>

<button class="add-food">
  <%= link_to 'Add food', new_food_path, class: 'nav-link' %>
</button>

<div>
  <% if @foods.any? %>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Measurement Unit</th>
          <th>Unit Price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td><%= food.price %></td>
            <td>
              <%= button_to 'Delete', food, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No foods available.</p>
  <% end %>
</div>

app/views/foods/new.html.erb
<%= form_with model: @food, url: foods_path, local: true do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, name: 'food[name]' %>
  </div>

  <div class="field">
    <%= form.label :measurement_unit %>
    <%= form.text_field :measurement_unit, name: 'food[measurement_unit]' %> 
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, name: 'food[price]' %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, name: 'food[quantity]' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Food' %>
  </div>
<% end %>

app/views/foods/show.html.erb
<h2>This is foods page</h2>

<%= link_to 'Add food', new_food_path, class: 'nav-link' %>

<div>
  <% if @foods.any? %>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Measurement Unit</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td><%= food.price %></td>
            <td><%= food.quantity %></td>
            <td>
              <%= button_to 'Delete', food, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No foods available.</p>
  <% end %>
</div>

app/views/layouts/_navabar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Recipe App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Recipes', recipes_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Foods', foods_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
         <%= link_to 'Public recipes', '/public_recipes/index', class: 'nav-link'  %>
        </li>
        <% if current_user %>
          <li class="nav-item">
             <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } ,class: 'nav-link'%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "recipe", "data-turbo-track": "reload"%>
    <%= stylesheet_link_tag "food", "data-turbo-track": "reload"%>
  </head>
  <body>
<%= render "layouts/navabar" %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>   
  </body>
</html>

app/views/public_recipes/index.html.erb
    <h1>Public Recipes</h1>
    <% @public_recipes.each do |recipe|%>
      
        <article>
          <div>
          <%= link_to recipe_path(recipe) do%>
              <p><strong><%= recipe.name%></strong></p>
          <% end %>
              <p>By: <%= recipe.user.name%></p>
          </div>
          <div>
            <p>Total food items: <%= recipe.foods.count %></p>
            <p>Total price: $<%= recipe.foods.sum(:price) %></p>
          </div>
        </article>
      
    <% end %>

app/views/reciepes/generate_shopping_list.html.erb
<div class="container">
  <h2 class="mt-4">Generate Shopping List</h2>
  <div class="row mt-4">
    <div class="col-md-6">
      <p>Amount of food items to buy: <%= @required_foods.to_a.count %></p>
      <p>Total Value of food needed: <%= number_to_currency(@total_value) %></p>
    </div>
  </div>

  <h3 class="mt-4">Required Food Items</h3>
  <table class="table table-bordered mt-2">
    <thead>
      <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Measurement Unit</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @required_foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.quantity %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= number_to_currency(food.quantity.to_i * food.price.to_f) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Back to Recipe', recipe_path(@recipe), class: 'btn btn-primary mt-4' %>
</div>

app/views/reciepes/show.html.erb
<div class="recipe-show-page">
  <div class="recipe-header">
   <% if flash[:notice].present? %>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
   <% end %>
    <h2><%= @recipe.name %></h2>
    <div class="top-line">
      <span>Preparation Time: <%= @recipe.preparation_time %> minutes</span>
      <span>
      <%= form_for @recipe do |f| %>
        <% if current_user == @recipe.user %>
          <% if @recipe.public %>
            <%= button_to  'Make Private ', recipe_path(@recipe), method: :patch, class: "btn btn-primary btn-sm" %>
         <% else %>
            <%= button_to  'Make public', recipe_path(@recipe), method: :patch, class: 'btn btn-primary btn-sm' %>
          <% end %>
        <% end %>
        <% end %>
      </span>
    </div>
  </div>
  <p>Cooking Time: <%= @recipe.cooking_time %> minutes</p>
  <p>Description: <%= @recipe.description %></p>
  <div class="recipe-show-button-container">
    <button class='btn btn-primary' id='gen-btn'>Generate Shopping List</button>

  <% if current_user == @recipe.user %>
      <%= link_to 'Add Ingredient', add_ingredient_recipe_path(@recipe), class: 'btn btn-primary' %>
    <% end %>
  </div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <% if current_user == @recipe.user %>
      <th>Action</th> <!-- Add an Action column -->
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @recipe_food.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.quantity %> <%= food.measurement_unit %></td>
        <td><%= number_to_currency(food.price) %></td>
        <% if current_user == @recipe.user %>
        <td>
            <%= form_tag(remove_food_recipe_path(@recipe, food_id: food.id), method: :delete) do %>
            <%= submit_tag 'Remove Food', class: 'btn btn-danger btn-sm' %>
            <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= link_to 'Back to Recipes', recipes_path %>
<%= render 'modal' %>
<script>
  const genBtn = document.querySelector('#gen-btn');
  genBtn.addEventListener('click', () => {
    const modal = document.querySelector('.shopping-list-modal');
    modal.style.display = 'block';
  });
</script>

app/views/recipes/_add_ingredient_form.html.erb
<h3>Add Ingredient</h3>
<%= form_for @recipe, url: add_ingredient_recipe_path(@recipe), method: :post do |f| %>
  <div class="form-group">
    <%= f.label :food_ids, 'Select Ingredient' %>
    <%= f.collection_select :food_ids, @foods_not_in_recipe, :id, :name, {}, multiple: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Add Ingredients', class: 'btn btn-primary' %>
  </div>
<% end %>

<script>
  function removeEmptyValues() {
    const selectElement = document.querySelector("#recipe_food_ids");
    const selectedOptions = Array.from(selectElement.selectedOptions);

    // Remove empty values ("" is empty)
    const filteredSelectedValues = selectedOptions.map(option => option.value).filter(value => value !== "");

    // Update the form field with the filtered values
    selectElement.value = filteredSelectedValues;
  }
</script>

app/views/recipes/_modal.html.erb
<section class='shopping-list-modal'>
  <h2> generating shopping list </h2>
  <h3> Choose an inventory to use</h3>
  <%= form_with url: choose_inventory_recipe_path(@recipe), method: :post do |f| %>
    <%= f.select :inventory_id, options_from_collection_for_select(current_user.inventories, :id, :name) %>
    <%= f.submit "Choose this inventory", class: 'btn btn-primary' %>
  <% end %>
</section>

app/views/recipes/add_ingredient.html.erb
<h3>Add Ingredient</h3>
<%= form_for @recipe, url: add_ingredient_recipe_path(@recipe), method: :post do |f| %>
  <div class="form-group">
    <%= f.label :food_ids, 'Select Ingredient' %>
    <%= f.collection_select :food_ids, @foods_not_in_recipe, :id, :name, {}, multiple: true, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>

  <div class="form-group">
    <%= f.submit 'Add Ingredients', class: 'btn btn-primary' %>
  </div>
<% end %>

<script>
  function removeEmptyValues() {
    const selectElement = document.querySelector("#recipe_food_ids");
    const selectedOptions = Array.from(selectElement.selectedOptions);

    // Remove empty values ("" is empty)
    const filteredSelectedValues = selectedOptions.map(option => option.value).filter(value => value !== "");

    // Update the form field with the filtered values
    selectElement.value = filteredSelectedValues;
  }
</script>

app/views/recipes/generate_shopping_list.html.erb
<div class="container">
  <h2 class="mt-4">Shopping List</h2>
  <div class="row mt-4">
    <div class="col-md-6">
      <p>Amount of food items to buy: <%= @required_foods.to_a.count %></p>
      <p>Total Value of food needed: <%= number_to_currency(@total_value) %></p>
    </div>
  </div>

  <h3 class="mt-4">Required Food Items</h3>
  <table class="table table-bordered mt-2">
    <thead>
      <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Measurement Unit</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @required_foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.quantity %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= number_to_currency(food.quantity.to_i * food.price.to_f) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Back to Recipe', recipe_path(@recipe), class: 'btn btn-primary mt-4' %>
</div>

app/views/recipes/index.html.erb
<h1>My Recipes</h1>

  <% @recipes.each do |recipe| %>
  <article>    
      <div>
      <p><%= link_to recipe.name, recipe, class:'recipe-name' %></p>
      <p><%= button_to 'Remove', recipe, method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure?' } if recipe.user == current_user %></p>
      </div>
       <div>
        <span><%= recipe.description %></span>
       </div>
   </article>
  <% end %>

<%# add a new recipe %>
<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1> New Recipe </h1>
<%= form_for @recipe do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :preparation_time %><br>
    <%= f.text_field :preparation_time %>
  </div>
  <div class="field">
    <%= f.label :cooking_time %><br>
    <%= f.text_field :cooking_time %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :public %><br>
    <%= f.check_box :public %>
  </div>
  <%= f.submit class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/recipes/show.html.erb
<div class="recipe-show-page">
  <div class="recipe-header">   
    <h2><%= @recipe.name %></h2>
    <div class="top-line">
      <span>Preparation Time: <%= @recipe.preparation_time %> minutes</span>
      <span>
      <%= form_for @recipe do |f| %>
        <% if current_user == @recipe.user %>
          <% if @recipe.public %>
            <%= button_to  'Make Private ', recipe_path(@recipe), method: :patch, class: "btn btn-primary btn-sm" %>
         <% else %>
            <%= button_to  'Make public', recipe_path(@recipe), method: :patch, class: 'btn btn-primary btn-sm' %>
          <% end %>
        <% end %>
        <% end %>
      </span>
    </div>
  </div>
  <p>Cooking Time: <%= @recipe.cooking_time %> minutes</p>
  <p>Description: <%= @recipe.description %></p>
  <div class="recipe-show-button-container">   
  <%= button_to 'Generate Shopping List', generate_shopping_list_recipe_path(@recipe), method: :get,class: 'btn btn-primary' %>
  <% if current_user == @recipe.user %>
      <%= link_to 'Add Ingredient', add_ingredient_recipe_path(@recipe), class: 'btn btn-primary' %>
    <% end %>
  </div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <% if current_user == @recipe.user %>
      <th>Action</th> <!-- Add an Action column -->
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @recipe_food.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.quantity %> <%= food.measurement_unit %></td>
        <td><%= number_to_currency(food.price) %></td>
        <% if current_user == @recipe.user %>
        <td>
            <%= form_tag(remove_food_recipe_path(@recipe, food_id: food.id), method: :delete) do %>
            <%= submit_tag 'Remove Food', class: 'btn btn-danger btn-sm' %>
            <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= link_to 'Back to Recipes', recipes_path %>